### ISSUE TITLE
Traceback/index out of range 错误

### ISSUE THREAD

**Issue by kongsket** [mengzonefire/twitter-media-downloader#11]
首先鼓掌一下，用起来还是非常舒服的
但是似乎是推特api的问题，超过3200条推文的推主将会无法爬取，本地并出现如下报错
Traceback (most recent call last):
  File "twitter-media-downloader.py", line 37, in <module>
  File "twitter-media-downloader.py", line 28, in main
  File "common\console.py", line 33, in cmdMode
  File "common\console.py", line 33, in cmdMode
  File "common\console.py", line 30, in cmdMode
  File "common\console.py", line 43, in startCrawl
  File "common\console.py", line 53, in urlHandler
  File "task\baseTask.py", line 29, in start
  File "task\userMediaTask.py", line 47, in getDataList
IndexError: list index out of range
可否增加限制推文范围（如最近三千条）或者使用如twint的方式来跳过限制呢

**Comment by mengzonefire** [comment]
脚本最新版已经采用了分批获取的方式避免这个问题, 碰到的报错应该是其他原因导致的, 反馈下爬取报错的推主链接我排查下

**Comment by kongsket** [comment]
![图片](https://user-images.githubusercontent.com/63382877/150664531-d1ee2554-2d75-470f-9e31-da7064e925dd.png)
https://twitter.com/trump_chinese
在1.2.1下的情况

**Comment by mengzonefire** [comment]
48aa7ac 已修复, 原因是该推主的userMedia接口返回数据不知为何包含一条没有media的推文:

https://twitter.com/Trump_Chinese/status/1347905548549820417

导致脚本匹配不到对应数据而报错
