### ISSUE TITLE
哥，我是新手，我打开python3运行那个。py文件，但是报错了这是为啥呀，麻烦大佬

### ISSUE THREAD

**Issue by gezhenghao1999** [mengzonefire/twitter-media-downloader#13]
"C:\Program Files\Python38\python.exe" C:/Users/Acer/Desktop/twitter-media-downloader-1.2.1/twitter-media-downloader.py
Traceback (most recent call last):
  File "C:/Users/Acer/Desktop/twitter-media-downloader-1.2.1/twitter-media-downloader.py", line 10, in <module>
    from common.const import *
  File "C:\Users\Acer\Desktop\twitter-media-downloader-1.2.1\common\const.py", line 4, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

进程已结束，退出代码为 1

**Comment by mengzonefire** [comment]
pip install requests
