### ISSUE TITLE
media 我怎么下不了

### ISSUE THREAD

**Issue by gxusb** [mengzonefire/twitter-media-downloader#40]
python3 twitter-media-downloader.py https://twitter.com/Yaorenmao_neko/media

<img width="884" alt="image" src="https://user-images.githubusercontent.com/105532932/224993591-df2ff1f1-3650-45d7-8681-c87cbb3a0bf4.png">

```log
Traceback (most recent call last):
  File "/Users/ljn/Desktop/MyProject/twitter-media-downloader/task/baseTask.py", line 46, in parseData
    cursor, rest_id_list = parseData(
  File "/Users/ljn/Desktop/MyProject/twitter-media-downloader/common/tools.py", line 609, in parseData
    rest_id_list.append(twtId)
AttributeError: 'str' object has no attribute 'append'
```

**Comment by mengzonefire** [comment]
因为这是dev分支，我还没写完

1.3.0这个版本请先等我写完release了再使用，没写完就先使用release里的1.2.5

**Comment by mengzonefire** [comment]
[047ea94](https://github.com/mengzonefire/twitter-media-downloader/commit/047ea94f505a1d513569770836bb5809394a1ec0)

修了，有别的问题欢迎反馈
