### ISSUE TITLE
新手：运行之后报这个错误怎么解决

### ISSUE THREAD

**Issue by sola222** [mengzonefire/twitter-media-downloader#52]
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

E:\tui130>python tui.py
Traceback (most recent call last):
  File "tui.py", line 10, in <module>
    from common.console import cmdMode, startCrawl
  File "E:\tui130\common\console.py", line 9, in <module>
    from task.singlePageTask import SinglePageTask
  File "E:\tui130\task\singlePageTask.py", line 14, in <module>
    from common.tools import getHttpText
  File "E:\tui130\common\tools.py", line 284, in <module>
    def getUserId(userName: str) -> int | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

E:\tui130>

**Comment by ji03mmy18** [comment]
應該是以這個指令執行才對：
```bash
python twitter-media-downloader.py
```

正常狀況下，就會看到：
```
输入命令数字或链接 (支持批量, 一行一条, 双击回车确认)

0.退出脚本
1.设置cookie
2.设置网络代理
3.设置下载参数

请输入：
```

就可以開始使用了。

**Comment by sola222** [comment]
需要特定的python版本吗，3.8.6 win7x64可以吗。我运行python twitter-media-downloader.py 还是提示上面那个错误
